### PR TITLE
Add clean command

### PR DESCRIPTION
**Pull request by fdaciuk**
Hey @developit! Are you kidding me? One more awesome project! Nice job :D 

I needed to add a simple command before run `npm start`, because I was getting this error:

``` console
> dropfox@1.0.0 build:assets /code/dropfox
> ncp src/assets build/assets

There were errors during the copy.
Error: ENOENT: no such file or directory, mkdir '/code/dropfox/build/assets'
```

I think it doesn't work on Windows (at least, not in default cmd). I don't know what we can do in this case. Maybe use a NodeJS script to do the same thing. What do you think?

### CODE REVIEW

**Comment by developit** [comment]
Hmm - I haven't tested this on Windows yet. I'm thinking there are some file paths that need to be made dynamic.  Are you still getting this error after adding the clean command?

**Comment by fdaciuk** [comment]
No. After clean command, the app works well =)

**Comment by developit** [comment]
oh wow, that's actually a huge surprise for me hahaha

**Comment by fdaciuk** [comment]
Actually, I couldn't make the app to work yet. Just build it haha xD
I'm getting a 400 error =/

At the first load, the screen doesn't load anything:

selection_180

After to press Ctrl + R, the interface is shown, but with a 400 error in a popup:

selection_181

**Comment by developit** [comment]
Ahh, that's the API Key being mismatched to the redirect URI.  In the Dropbox API console, make sure you have the URL `https://dropfox.firebaseapp.com/dropbox/oauth_receiver.html` whitelisted.

**Comment by fdaciuk** [comment]
And now it works! :dancer: :dancer: :sparkles:

**Comment by developit** [comment]
WOOT!

**Comment by developit** [comment]
Now we just need @connors to make a photon variant that fits in a bit better on Windows & Linux.

**Pull request merged**
